--
--    Copyright ${license.git.copyrightYears} the original author or authors.
--
--    Licensed under the Apache License, Version 2.0 (the "License");
--    you may not use this file except in compliance with the License.
--    You may obtain a copy of the License at
--
--       http://www.apache.org/licenses/LICENSE-2.0
--
--    Unless required by applicable law or agreed to in writing, software
--    distributed under the License is distributed on an "AS IS" BASIS,
--    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
--    See the License for the specific language governing permissions and
--    limitations under the License.
--

DROP TABLE book;
CREATE TABLE book (
-- id                INT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
id                INT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 5, INCREMENT BY 1),
name              VARCHAR(255) NOT NULL,
detail            VARCHAR(255) NOT NULL,
price             numeric default 0,
create_time       TIMESTAMP NOT NULL,
PRIMARY KEY (id)
);



INSERT INTO book (id, name, detail, price, create_time) VALUES (1, '《平凡的世界》',  '97年出饭',  100,  '2007-12-05-00.00.00');
INSERT INTO book (id, name, detail, price, create_time) VALUES (2, '《他》',          '侵权',  23.1, '2008-01-12-00.00.00');
INSERT INTO book (id, name, detail, price, create_time) VALUES (3, '《时间简史》',    '霍金写的书',  102, '2007-12-05-00.00.00');
INSERT INTO book (id, name, detail, price, create_time) VALUES (4, '《野性的呼呼》',  '外文书籍',  102, '2008-01-12-00.00.00');
